# 1. Database Connection (Cloud MongoDB)


# 2. Server Settings
server.port=8080
spring.application.name=HardwarePro-V2

# 3. UI Settings (Thymeleaf)

l

# 4. File Upload (Scanner ke liye zaruri hai)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 5. Logging (Galti dhoondne ke liye)
logging.level.org.springframework.data.mongodb=DEBUG
# Java ko batana ki templates ab project ke root folder mein hain
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true

# Java ko batana ki static files (agar hain) kahan hain
spring.web.resources.static-locations=file:resources/
# SRV hata kar seedha host use karein
spring.data.mongodb.uri=mongodb://aryan310618_db_user:9lJsZeXfgHKn3ZrR@ac-rlhyubq-shard-00-00.mttebrq.mongodb.net:27017,ac-rlhyubq-shard-00-01.mttebrq.mongodb.net:27017,ac-rlhyubq-shard-00-02.mttebrq.mongodb.net:27017/?ssl=true&replicaSet=atlas-lhlaj6-shard-0&authSource=admin&appName=mamadukan
spring.data.mongodb.database=mamadukan
